name: employees
description: A new Flutter application.

publish_to: 'none'
version: 0.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  intl: ^0.16.1
  moor: ^3.1.0
  moor_ffi: ^0.6.0
  path_provider: ^1.6.10
  path: ">=1.6.4 <1.8.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ">=1.9.0 <2.0.0"
  moor_generator: ^3.1.0

flutter:
  uses-material-design: true
