name: employees
description: A new Flutter application.

publish_to: 'none'
version: 0.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  intl: ^0.16.1
  uuid: ^2.0.4
  dataclass: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ">=1.9.0 <2.0.0"
  dataclass_generator: ^0.3.0

flutter:
  uses-material-design: true
